/**
 * Central registry of all React hooks in this course.
 * HookHub reads metadata; App uses hookLabs map for routing.
 */

export const HOOK_REGISTRY = [
  {
    id: 'useState',
    name: 'useState',
    tagline: 'Remember data that changes over time',
    description: 'Store component memory, trigger re-renders, update UI when data changes.',
    level: 'beginner',
    lessons: 7,
    color: '#61dafb',
    category: 'state',
  },
  {
    id: 'useReducer',
    name: 'useReducer',
    tagline: 'State with actions and a reducer function',
    description: 'Manage complex state transitions like Redux — dispatch actions, pure reducer updates.',
    level: 'intermediate',
    lessons: 5,
    color: '#764abc',
    category: 'state',
  },
  {
    id: 'useContext',
    name: 'useContext',
    tagline: 'Share data without prop drilling',
    description: 'Pass theme, user, or settings through the tree without passing props at every level.',
    level: 'intermediate',
    lessons: 5,
    color: '#f7df1e',
    category: 'state',
  },
  {
    id: 'useRef',
    name: 'useRef',
    tagline: 'Mutable box that survives re-renders',
    description: 'Access DOM nodes, store timers, keep values without causing re-renders.',
    level: 'beginner',
    lessons: 5,
    color: '#ff6b6b',
    category: 'refs',
  },
  {
    id: 'useEffect',
    name: 'useEffect',
    tagline: 'Sync with the outside world',
    description: 'Run side effects after render — fetch data, subscriptions, timers, document title.',
    level: 'beginner',
    lessons: 6,
    color: '#4ecdc4',
    category: 'effects',
  },
  {
    id: 'useLayoutEffect',
    name: 'useLayoutEffect',
    tagline: 'Effect before the browser paints',
    description: 'Measure DOM or apply layout changes before user sees flicker.',
    level: 'advanced',
    lessons: 4,
    color: '#45b7d1',
    category: 'effects',
  },
  {
    id: 'useInsertionEffect',
    name: 'useInsertionEffect',
    tagline: 'Inject styles before layout',
    description: 'For CSS-in-JS libraries — run before DOM mutations from useLayoutEffect.',
    level: 'advanced',
    lessons: 3,
    color: '#96ceb4',
    category: 'effects',
  },
  {
    id: 'useMemo',
    name: 'useMemo',
    tagline: 'Cache expensive calculations',
    description: 'Skip heavy work when dependencies unchanged; stabilize object references.',
    level: 'intermediate',
    lessons: 11,
    color: '#aa3bff',
    category: 'performance',
  },
  {
    id: 'useCallback',
    name: 'useCallback',
    tagline: 'Cache function references',
    description: 'Keep the same function reference between renders for memoized children.',
    level: 'intermediate',
    lessons: 5,
    color: '#e056fd',
    category: 'performance',
  },
  {
    id: 'useTransition',
    name: 'useTransition',
    tagline: 'Mark updates as non-urgent',
    description: 'Keep UI responsive during heavy state updates with isPending feedback.',
    level: 'advanced',
    lessons: 4,
    color: '#ff9f43',
    category: 'performance',
  },
  {
    id: 'useDeferredValue',
    name: 'useDeferredValue',
    tagline: 'Defer showing stale UI',
    description: 'Lag behind urgent state so typing stays smooth while lists re-filter.',
    level: 'advanced',
    lessons: 4,
    color: '#f368e0',
    category: 'performance',
  },
  {
    id: 'useImperativeHandle',
    name: 'useImperativeHandle',
    tagline: 'Customize the ref exposed to parents',
    description: 'Expose focus(), scroll(), or play() from child without breaking encapsulation.',
    level: 'advanced',
    lessons: 4,
    color: '#576574',
    category: 'refs',
  },
  {
    id: 'useId',
    name: 'useId',
    tagline: 'Unique IDs for accessibility',
    description: 'Stable ids for label/htmlFor pairs — works with server rendering.',
    level: 'beginner',
    lessons: 3,
    color: '#10ac84',
    category: 'misc',
  },
  {
    id: 'useDebugValue',
    name: 'useDebugValue',
    tagline: 'Label custom hooks in DevTools',
    description: 'Show friendly state labels when inspecting custom hooks in React DevTools.',
    level: 'advanced',
    lessons: 3,
    color: '#5f27cd',
    category: 'misc',
  },
  {
    id: 'useSyncExternalStore',
    name: 'useSyncExternalStore',
    tagline: 'Subscribe to external stores',
    description: 'Safely subscribe to browser APIs or global stores outside React state.',
    level: 'advanced',
    lessons: 4,
    color: '#222f3e',
    category: 'misc',
  },
  {
    id: 'useOptimistic',
    name: 'useOptimistic',
    tagline: 'Show instant UI while waiting',
    description: 'Optimistically update UI before server confirms — rollback on error.',
    level: 'advanced',
    lessons: 4,
    color: '#00d2d3',
    category: 'react19',
  },
  {
    id: 'useActionState',
    name: 'useActionState',
    tagline: 'State from async server actions',
    description: 'Handle pending, result, and error from form actions in one hook.',
    level: 'advanced',
    lessons: 4,
    color: '#54a0ff',
    category: 'react19',
  },
  {
    id: 'useFormStatus',
    name: 'useFormStatus',
    tagline: 'Pending state from parent form',
    description: 'Child buttons know if the parent form submission is still running.',
    level: 'intermediate',
    lessons: 3,
    color: '#48dbfb',
    category: 'react19',
  },
]

export const HOOK_CATEGORIES = [
  { id: 'state', label: 'State' },
  { id: 'effects', label: 'Effects' },
  { id: 'refs', label: 'Refs' },
  { id: 'performance', label: 'Performance' },
  { id: 'misc', label: 'Other' },
  { id: 'react19', label: 'React 19' },
]
